import os
import re

# Load base sample2 HTML content
with open('test-biscamaze-lf-sample2.html', 'r', encoding='utf-8') as f:
    sample2_html = f.read()

# Product catalog dictionary
PRODUCTS = {
    'product-biscamaze-lf.html': {
        'title': 'BISCAMAZE® LF - Protease Biscuit & Cookie Improver | Praras Biosciences',
        'meta_desc': 'BISCAMAZE® LF by Praras Biosciences: High-performance Protease (E-1101) biscuit improver. Boosts stack height by +5%, reduces fat up to 20%, and cuts SMBS by 40–60%.',
        'og_title': 'BISCAMAZE® LF - High-Performance Biscuit & Cookie Improver',
        'og_desc': 'Enzymatic protease formulation (E-1101) by Praras Biosciences to enhance browning, crispiness, stack height (+5%), and reduce fat up to 20%.',
        'cat_crumb': 'Biscuit Improvers',
        'cat_crumb_link': 'biscuits-cookies.html',
        'badge': 'Protease (E-1101) Formulation',
        'hero_title': 'BISCAMAZE® LF',
        'hero_sub': 'Precision enzymatic formulation designed for commercial biscuit & cookie manufacturers to optimize dough rheology, enhance stack height, and cut ingredient costs.',
        'stat1_num': '+5%',
        'stat1_txt': 'Stack Height Gain',
        'stat2_num': 'Up to 20%',
        'stat2_txt': 'Fat Reduction',
        'stat3_num': '40–60%',
        'stat3_txt': 'SMBS Usage Cut',
        'image': 'assets/images/biscamaze_lf.svg',
        'app': 'Biscuits & Cookies',
        'active': 'Protease (E-1101)',
        'activity': 'NLT 12,000 TU/g',
        'dosage': '20–100 g / 100 kg flour',
        'spotlight': 'Enhances browning and crispiness, boosts stack height by 5%, cuts fat up to 20% and SMBS by 40–60%—all with cost-effective efficiency.',
        'meter1_title': 'Biscuit Stack Height Gain',
        'meter1_val': '+5% Gain',
        'meter1_w': '92%',
        'meter2_title': 'Fat Content Reduction Capacity',
        'meter2_val': 'Up to 20% Cut',
        'meter2_w': '85%',
        'meter3_title': 'SMBS Additive Usage Reduction',
        'meter3_val': '40–60% Reduction',
        'meter3_w': '90%',
        'enumbers': ['E-1101 (Protease)', 'E-407a (Processed Eucheuma)', 'E-415 (Xanthan Gum)', 'E-1405 (Enzyme Treated Starch)'],
        'b1_t': 'Texture & Browning', 'b1_tag': 'Crispy Bite', 'b1_d': 'Improves texture and overall quality such as browning and crispiness in biscuits and crackers.',
        'b2_t': 'Stack Height Boost', 'b2_tag': '+5% Height', 'b2_d': 'Increases biscuit stack height up to 5% with maximum cost effectiveness.',
        'b3_t': 'Fat Reduction', 'b3_tag': 'Up to 20% Cut', 'b3_d': 'Helps in fat reduction up to 20% or more depending on fat percentage.',
        'b4_t': 'SMBS Reduction', 'b4_tag': '40–60% Cut', 'b4_d': 'SMBS additive usage can be reduced by 40–60% in dough formulation.',
        'b5_t': 'Cost Efficiency', 'b5_tag': 'Commercial ROI', 'b5_d': 'Delivers substantial batch cost reduction for high-volume biscuit & cookie operations.',
        'b6_t': 'Sensory Impression', 'b6_tag': 'Quality Boost', 'b6_d': 'Significantly elevates customer perception and product crispiness.',
        'sensory_val': 'It offers crispy bite',
        'table_name': 'BISCAMAZE® LF',
        'table_app': 'Biscuits & Cookies',
        'table_active': 'Protease (E-1101)',
        'table_activity': 'NLT 12000 TU/g',
        'table_dosage': '20 to 100 g per 100 kg flour',
        'table_reg': 'Conforms to FSSR 2011 / 2016 Food Safety Standards'
    },

    'product-biscamaze-dh.html': {
        'title': 'BISCAMAZE® DH - High Activity Protease Biscuit Improver | Praras Biosciences',
        'meta_desc': 'BISCAMAZE® DH by Praras Biosciences: High-activity Protease (E-1101) NLT 40,000 TU/g for hard dough biscuits. Relaxes gluten, prevents shrinkage, and increases stack height (+6%).',
        'og_title': 'BISCAMAZE® DH - Concentrated Hard Dough Biscuit Improver',
        'og_desc': 'Concentrated high-activity protease formulation (E-1101) NLT 40,000 TU/g to eliminate snap-back, improve sheetability, and boost stack height.',
        'cat_crumb': 'Biscuit Improvers',
        'cat_crumb_link': 'biscuits-cookies.html',
        'badge': 'High Activity Protease (NLT 40,000 TU/g)',
        'hero_title': 'BISCAMAZE® DH',
        'hero_sub': 'Concentrated high-activity protease formulation for hard dough biscuits, reducing mixing time, preventing shrinkage, and enhancing stack height.',
        'stat1_num': '+6%',
        'stat1_txt': 'Stack Height Gain',
        'stat2_num': '40,000 TU/g',
        'stat2_txt': 'High Activity Level',
        'stat3_num': '50%',
        'stat3_txt': 'SMBS Reduction',
        'image': 'assets/images/biscamaze_dh.svg',
        'app': 'Hard Dough Biscuits & Crackers',
        'active': 'Protease (E-1101)',
        'activity': 'NLT 40,000 TU/g',
        'dosage': '5–25 g / 100 kg flour',
        'spotlight': 'Concentrated enzyme power to relax gluten, eliminate dough snap-back, improve sheetability, and ensure uniform stack dimensions.',
        'meter1_title': 'Hard Dough Gluten Relaxation',
        'meter1_val': '95% Efficiency',
        'meter1_w': '95%',
        'meter2_title': 'Shrinkage & Warping Prevention',
        'meter2_val': '90% Cut',
        'meter2_w': '90%',
        'meter3_title': 'Dough Mixing Time Reduction',
        'meter3_val': '25% Saved',
        'meter3_w': '85%',
        'enumbers': ['E-1101 (Protease)', 'E-1405 (Enzyme Treated Starch)'],
        'b1_t': 'Gluten Relaxation', 'b1_tag': 'Zero Snap-back', 'b1_d': 'Relaxes hard wheat gluten matrices for smooth dough rolling and sheet formation.',
        'b2_t': 'Dimensional Control', 'b2_tag': 'Uniform Size', 'b2_d': 'Eliminates shrinkage and warping during high-speed baking line operations.',
        'b3_t': 'Concentrated Dosage', 'b3_tag': 'Ultra Low Use', 'b3_d': 'Requires only 5–25g per 100kg flour due to high NLT 40,000 TU/g potency.',
        'b4_t': 'SMBS Replacement', 'b4_tag': 'Chemical Cut', 'b4_d': 'Replaces sodium metabisulfite safely without sulfur dioxide residues.',
        'b5_t': 'Stack Height Gain', 'b5_tag': '+6% Height', 'b5_d': 'Increases biscuit stack height for better retail packaging density.',
        'b6_t': 'Crisp & Airy Bite', 'b6_tag': 'Enhanced Snap', 'b6_d': 'Produces delicate crumb structures with excellent mouthfeel and snap.',
        'sensory_val': 'It offers crisp texture with light delicate crunch',
        'table_name': 'BISCAMAZE® DH',
        'table_app': 'Hard Dough Biscuits & Crackers',
        'table_active': 'Protease (E-1101)',
        'table_activity': 'NLT 40000 TU/g',
        'table_dosage': '5 to 25 g per 100 kg flour',
        'table_reg': 'Conforms to FSSR 2011 / 2016 Food Safety Standards'
    },

    'product-biscamaze-cw.html': {
        'title': 'BISCAMAZE® CW - Wafer Batter & Sheet Conditioner | Praras Biosciences',
        'meta_desc': 'BISCAMAZE® CW by Praras Biosciences: Specialized enzyme-hydrocolloid blend for wafer batter preparation. Reduces viscosity, water usage, and sheet breakage.',
        'og_title': 'BISCAMAZE® CW - Wafer Batter & Sheet Conditioner',
        'og_desc': 'Specialized enzyme & hydrocolloid blend to lower wafer batter viscosity, prevent sheet cracking, and cut baking energy consumption.',
        'cat_crumb': 'Wafer Improvers',
        'cat_crumb_link': 'wafers.html',
        'badge': 'Wafer Rheology & Binding Complex',
        'hero_title': 'BISCAMAZE® CW',
        'hero_sub': 'Specialized enzyme-hydrocolloid blend for wafer batter preparation, lowering viscosity, reducing water usage, and preventing wafer sheet breakage.',
        'stat1_num': 'Lower',
        'stat1_txt': 'Batter Viscosity',
        'stat2_num': 'Zero',
        'stat2_txt': 'Sheet Cracking',
        'stat3_num': '-15%',
        'stat3_txt': 'Water Usage',
        'image': 'assets/images/biscamaze_cw.svg',
        'app': 'Wafers & Ice Cream Cones',
        'active': 'Enzyme & Hydrocolloid Blend',
        'activity': 'Batter Viscosity & Binding Matrix',
        'dosage': '20–80 g / 100 kg flour',
        'spotlight': 'Enhances wafer sheet uniformity, prevents oven plate sticking, improves crispiness, and reduces energy consumption during baking.',
        'meter1_title': 'Batter Fluidity & Pumping Control',
        'meter1_val': '98% Flow',
        'meter1_w': '98%',
        'meter2_title': 'Sheet Strength & Breakage Cut',
        'meter2_val': '95% Strength',
        'meter2_w': '95%',
        'meter3_title': 'Energy Savings via Water Cut',
        'meter3_val': '15% Energy Cut',
        'meter3_w': '88%',
        'enumbers': ['E-1101 (Protease)', 'E-415 (Xanthan Gum)', 'E-407 (Carrageenan)'],
        'b1_t': 'Uniform Batter Flow', 'b1_tag': 'Smooth Pumping', 'b1_d': 'Maintains ideal batter fluidity without sedimentation in holding tanks.',
        'b2_t': 'Sheet Integrity', 'b2_tag': 'Low Breakage', 'b2_d': 'Produces strong, crisp wafer sheets that withstand creaming and cutting.',
        'b3_t': 'Reduced Water Content', 'b3_tag': 'Energy Saver', 'b3_d': 'Allows lower water-to-flour ratios, speeding up baking time.',
        'b4_t': 'Non-stick Baking', 'b4_tag': 'Clean Release', 'b4_d': 'Ensures smooth release from automatic wafer baking plates.',
        'b5_t': 'Color Uniformity', 'b5_tag': 'Golden Surface', 'b5_d': 'Yields even golden browning across all wafer grid cells.',
        'b6_t': 'Extended Crispiness', 'b6_tag': 'Moisture Guard', 'b6_d': 'Preserves delicate crispiness under ambient humidity swings.',
        'sensory_val': 'It offers ultra-light golden crunch',
        'table_name': 'BISCAMAZE® CW',
        'table_app': 'Wafers & Ice Cream Cones',
        'table_active': 'Enzyme & Hydrocolloid Blend',
        'table_activity': 'Viscosity & Binding Matrix',
        'table_dosage': '20 to 80 g per 100 kg flour',
        'table_reg': 'Conforms to FSSR 2011 / 2016 Food Safety Standards'
    },

    'product-biscamaze-cw01.html': {
        'title': 'BISCAMAZE® CW01 - Premium Wafer Sheet Improver | Praras Biosciences',
        'meta_desc': 'BISCAMAZE® CW01 by Praras Biosciences: Advanced wafer conditioning formulation engineered to prevent batter starch retrogradation, eliminate waste, and enhance crispiness.',
        'og_title': 'BISCAMAZE® CW01 - Premium Wafer Sheet Improver',
        'og_desc': 'Advanced starch rheology complex preventing batter thickening, eliminating wafer sheet waste, and delivering gourmet bite quality.',
        'cat_crumb': 'Wafer Improvers',
        'cat_crumb_link': 'wafers.html',
        'badge': 'Starch Rheology & Downtime Guard',
        'hero_title': 'BISCAMAZE® CW01',
        'hero_sub': 'Advanced wafer conditioning formulation engineered to prevent batter starch retrogradation, eliminate wafer waste, and enhance crispiness.',
        'stat1_num': '100%',
        'stat1_txt': 'Downtime Stability',
        'stat2_num': '-35%',
        'stat2_txt': 'Wafer Sheet Waste',
        'stat3_num': '96%',
        'stat3_txt': 'Crispness Index',
        'image': 'assets/images/biscamaze_cw01.svg',
        'app': 'Premium Wafers & Cones',
        'active': 'Enzyme & Starch Complex',
        'activity': 'Starch Rheology Control',
        'dosage': '15–60 g / 100 kg flour',
        'spotlight': 'Prevents batter thickening during downtime, ensures consistent sheet weight, and delivers executive-grade bite quality.',
        'meter1_title': 'Batter Downtime Rheology Hold',
        'meter1_val': '100% Stable',
        'meter1_w': '100%',
        'meter2_title': 'Wafer Waste Reduction',
        'meter2_val': '35% Less Waste',
        'meter2_w': '90%',
        'meter3_title': 'Grid Pattern Fill Precision',
        'meter3_val': '98% Fill',
        'meter3_w': '98%',
        'enumbers': ['E-1101 (Protease)', 'E-415 (Xanthan Gum)'],
        'b1_t': 'Downtime Protection', 'b1_tag': 'No Thickening', 'b1_d': 'Prevents batter viscosity spikes even after hours in holding tanks.',
        'b2_t': 'Consistent Weight', 'b2_tag': 'Precision Sheets', 'b2_d': 'Guarantees exact wafer sheet weight for accurate filling ratios.',
        'b3_t': 'Reduced Waste', 'b3_tag': 'Max Yield', 'b3_d': 'Minimizes cracked or incomplete sheets on automated lines.',
        'b4_t': 'Fine Grid Detail', 'b4_tag': 'Flawless Pattern', 'b4_d': 'Fills intricate wafer plate designs with zero air pockets.',
        'b5_t': 'Enhanced Crispness', 'b5_tag': 'Velvety Crunch', 'b5_d': 'Imparts an upscale gourmet texture to flat and rolled wafers.',
        'b6_t': 'Clean Release', 'b6_tag': 'Zero Build-up', 'b6_d': 'Keeps baking irons free from carbonized starch residues.',
        'sensory_val': 'It offers exceptionally crisp delicate bite',
        'table_name': 'BISCAMAZE® CW01',
        'table_app': 'Premium Wafers & Cones',
        'table_active': 'Enzyme & Starch Complex',
        'table_activity': 'Starch Rheology Matrix',
        'table_dosage': '15 to 60 g per 100 kg flour',
        'table_reg': 'Conforms to FSSR 2011 / 2016 Food Safety Standards'
    },

    'product-textureaid-m.html': {
        'title': 'TEXTUREAID® M - Meat Yield & Texture Booster | Praras Biosciences',
        'meta_desc': 'TEXTUREAID® M by Praras Biosciences: Hydrocolloid & psyllium texturizer for processed meats. Increases cooking yield by +15%, improves water binding, and ensures juicy bite.',
        'og_title': 'TEXTUREAID® M - Meat Yield & Texture Booster',
        'og_desc': 'Psyllium-based meat hydrocolloid (NLT 50,000 IU/g) boosting cook yield (+15%), binding water, and preventing purge in sausages & nuggets.',
        'cat_crumb': 'Meat Texturizers',
        'cat_crumb_link': 'meat.html',
        'badge': 'Psyllium Husk & Hydrocolloid Matrix (NLT 50,000 IU/g)',
        'hero_title': 'TEXTUREAID® M',
        'hero_sub': 'Hydrocolloid & fiber-based texturizer for processed meat products, increasing cook yield, improving water binding, and enhancing juiciness.',
        'stat1_num': '+15%',
        'stat1_txt': 'Cooking Yield Gain',
        'stat2_num': '50,000 IU/g',
        'stat2_txt': 'Active Potency',
        'stat3_num': 'Zero',
        'stat3_txt': 'Package Purge',
        'image': 'assets/images/textureaid_m.svg',
        'app': 'Processed Meat, Sausages & Nuggets',
        'active': 'Psyllium Husk & Hydrocolloids',
        'activity': 'NLT 50,000 IU/g',
        'dosage': '0.5–2.0% of total mass',
        'spotlight': 'Binds free moisture and fat in emulsion meats, prevents purge in vacuum packs, and delivers a firm, juicy bite.',
        'meter1_title': 'Water Binding Capacity',
        'meter1_val': '98% Bound',
        'meter1_w': '98%',
        'meter2_title': 'Cook Loss Reduction',
        'meter2_val': '+15% Yield',
        'meter2_w': '92%',
        'meter3_title': 'High-Speed Slice Integrity',
        'meter3_val': '95% Clean Cut',
        'meter3_w': '95%',
        'enumbers': ['Natural Plant Hydrocolloids (Psyllium Husk Matrix)'],
        'b1_t': 'Water Binding', 'b1_tag': 'Zero Purge', 'b1_d': 'Retains natural juices and added water during processing and cold storage.',
        'b2_t': 'Increased Cooking Yield', 'b2_tag': '+15% Yield', 'b2_d': 'Minimizes cook loss in ovens, fryers, and smokehouses.',
        'b3_t': 'Succulent Texture', 'b3_tag': 'Juicy Bite', 'b3_d': 'Restores natural meat springiness and firmness without rubbery mouthfeel.',
        'b4_t': 'Fat Emulsification', 'b4_tag': 'Stable Matrix', 'b4_d': 'Prevents fat capping and oil separation in cooked sausages.',
        'b5_t': 'Excellent Sliceability', 'b5_tag': 'Clean Cut', 'b5_d': 'Prevents crumbling and tearing during high-speed industrial slicing.',
        'b6_t': 'Cost Reduction', 'b6_tag': 'Better Extension', 'b6_d': 'Reduces recipe cost per kg while maintaining premium meat quality.',
        'sensory_val': 'It offers firm juicy bite with natural spring',
        'table_name': 'TEXTUREAID® M',
        'table_app': 'Processed Meat & Poultry',
        'table_active': 'Psyllium Husk & Hydrocolloids',
        'table_activity': 'NLT 50000 IU/g',
        'table_dosage': '0.5% to 2.0% of total formulation',
        'table_reg': 'Conforms to FSSR 2011 / 2016 Food Safety Standards'
    },

    'product-textureaid-msk.html': {
        'title': 'TEXTUREAID® MSK - Viscoelastic Meat & Noodle Texturizer | Praras Biosciences',
        'meta_desc': 'TEXTUREAID® MSK by Praras Biosciences: Multi-functional hydrocolloid texturizer providing optimal viscoelastic balance, freeze-thaw stability, and water retention in meats and noodles.',
        'og_title': 'TEXTUREAID® MSK - Viscoelastic Hydrocolloid Texturizer',
        'og_desc': 'SVP-based hydrocolloid texturizer delivering freeze-thaw stability, high elasticity, and moisture retention in meats and noodles.',
        'cat_crumb': 'Meat & Noodle Texturizers',
        'cat_crumb_link': 'meat.html',
        'badge': 'Hydrocolloid & SVP Viscoelastic Complex',
        'hero_title': 'TEXTUREAID® MSK',
        'hero_sub': 'Multi-functional hydrocolloid texturizer providing optimal viscoelastic balance, water retention, and thermal stability in meats and noodles.',
        'stat1_num': '100%',
        'stat1_txt': 'Freeze-Thaw Stability',
        'stat2_num': 'High',
        'stat2_txt': 'Viscoelasticity',
        'stat3_num': 'Zero',
        'stat3_txt': 'Drip Loss',
        'image': 'assets/images/textureaid_msk.svg',
        'app': 'Meats, Noodles & Prepared Foods',
        'active': 'Hydrocolloid & SVP Complex',
        'activity': 'Viscoelastic Binding Matrix',
        'dosage': '0.3–1.5% of total mass',
        'spotlight': 'Enhances tensile strength, prevents moisture loss during freeze-thaw cycles, and maintains structural integrity.',
        'meter1_title': 'Freeze-Thaw Drip Loss Guard',
        'meter1_val': '100% Protection',
        'meter1_w': '100%',
        'meter2_title': 'Noodle & Meat Tensile Elasticity',
        'meter2_val': '94% Elastic',
        'meter2_w': '94%',
        'meter3_title': 'Thermal Retort Stability',
        'meter3_val': '98% Stable',
        'meter3_w': '98%',
        'enumbers': ['Hydrocolloid & SVP Natural Matrix'],
        'b1_t': 'Freeze-Thaw Resilience', 'b1_tag': 'Zero Drip Loss', 'b1_d': 'Protects frozen meats and noodles from drip loss upon thawing.',
        'b2_t': 'Elastic Firmness', 'b2_tag': 'Chewiness Boost', 'b2_d': 'Enhances bite firmness in both processed meats and extruded noodles.',
        'b3_t': 'High Viscoelasticity', 'b3_tag': 'Tensile Strength', 'b3_d': 'Prevents breakage during cooking and retorting operations.',
        'b4_t': 'Moisture Retention', 'b4_tag': 'Juicy Crumb', 'b4_d': 'Holds moisture evenly throughout the product mass.',
        'b5_t': 'Emulsion Stabilization', 'b5_tag': 'Uniform Blend', 'b5_d': 'Ensures homogeneous distribution of fats, water, and proteins.',
        'b6_t': 'Clean Flavor Profile', 'b6_tag': 'Neutral Taste', 'b6_d': 'Does not mask delicate meat or grain flavor notes.',
        'sensory_val': 'It offers firm elastic texture with zero purge',
        'table_name': 'TEXTUREAID® MSK',
        'table_app': 'Meats, Noodles & Prepared Foods',
        'table_active': 'Hydrocolloid & SVP Complex',
        'table_activity': 'High Viscoelastic Matrix',
        'table_dosage': '0.3% to 1.5% of total formulation',
        'table_reg': 'Conforms to FSSR 2011 / 2016 Food Safety Standards'
    },

    'product-textureaid-025.html': {
        'title': 'TEXTUREAID® 025 - Dough & Extrusion Conditioner | Praras Biosciences',
        'meta_desc': 'TEXTUREAID® 025 by Praras Biosciences: Advanced hydrocolloid blend reducing surface cracking, improving cook loss, and enhancing elasticity in pasta and noodles.',
        'og_title': 'TEXTUREAID® 025 - Dough & Extrusion Conditioner',
        'og_desc': 'Extrusion hydrocolloid matrix preventing noodle micro-cracks, reducing cook loss by 30%, and enhancing al dente elasticity.',
        'cat_crumb': 'Pasta & Noodle Improvers',
        'cat_crumb_link': 'pasta-and-noodles.html',
        'badge': 'Extrusion & Cook Loss Conditioning Matrix',
        'hero_title': 'TEXTUREAID® 025',
        'hero_sub': 'Advanced hydrocolloid blend designed to reduce surface cracking, improve cook loss, and enhance elasticity in pasta, noodles, and extruded foods.',
        'stat1_num': 'Zero',
        'stat1_txt': 'Micro-Cracks',
        'stat2_num': '-30%',
        'stat2_txt': 'Cooking Loss',
        'stat3_num': 'Al Dente',
        'stat3_txt': 'Noodle Elasticity',
        'image': 'assets/images/textureaid_025.svg',
        'app': 'Pasta, Instant Noodles & Extruded Snacks',
        'active': 'Hydrocolloid Blend',
        'activity': 'Extrusion Conditioning Matrix',
        'dosage': '0.2–1.0% of flour weight',
        'spotlight': 'Eliminates noodle strand breakage, improves water absorption during cooking, and ensures smooth machine extrusion.',
        'meter1_title': 'Extrusion Surface Smoothness',
        'meter1_val': '99% Smooth',
        'meter1_w': '99%',
        'meter2_title': 'Cooking Water Starch Retained',
        'meter2_val': '30% Less Loss',
        'meter2_w': '90%',
        'meter3_title': 'Frying Oil Barrier Protection',
        'meter3_val': 'Oil Reduced',
        'meter3_w': '88%',
        'enumbers': ['E-412 (Guar Gum)', 'E-415 (Xanthan Gum)'],
        'b1_t': 'Crack-Free Extrusion', 'b1_tag': 'Smooth Surface', 'b1_d': 'Prevents micro-cracks and surface checking during drying and frying.',
        'b2_t': 'Reduced Cook Loss', 'b2_tag': 'Clear Broth', 'b2_d': 'Keeps starch bound inside pasta/noodles, preventing murky cooking water.',
        'b3_t': 'Enhanced Elasticity', 'b3_tag': 'Firm Al Dente', 'b3_d': 'Delivers desirable al dente bite and noodle elasticity.',
        'b4_t': 'High Water Absorption', 'b4_tag': 'Greater Yield', 'b4_d': 'Increases cooked noodle yield without sogginess.',
        'b5_t': 'High-Speed Machinability', 'b5_tag': 'Zero Sticking', 'b5_d': 'Ensures smooth die extrusion and clean strand cutting.',
        'b6_t': 'Oil Cut in Fried Snacks', 'b6_tag': 'Healthier Product', 'b6_d': 'Forms a barrier layer that reduces oil absorption during frying.',
        'sensory_val': 'It offers firm elastic al dente texture',
        'table_name': 'TEXTUREAID® 025',
        'table_app': 'Pasta & Instant Noodles',
        'table_active': 'Hydrocolloid Blend',
        'table_activity': 'Extrusion Conditioning Matrix',
        'table_dosage': '0.2% to 1.0% of flour weight',
        'table_reg': 'Conforms to FSSR 2011 / 2016 Food Safety Standards'
    },

    'product-textureaid-clf.html': {
        'title': 'TEXTUREAID® CLF - Clear Noodle & Pasta Clarifier | Praras Biosciences',
        'meta_desc': 'TEXTUREAID® CLF by Praras Biosciences: Hydrocolloid clarifier imparting translucent sheen, high cooking stability, and non-stick texture to glass noodles and pasta.',
        'og_title': 'TEXTUREAID® CLF - Clear Noodle & Pasta Clarifier',
        'og_desc': 'Specialized hydrocolloid complex enhancing visual transparency, non-stick strand separation, and soup stability in clear noodles.',
        'cat_crumb': 'Pasta & Noodle Improvers',
        'cat_crumb_link': 'pasta-and-noodles.html',
        'badge': 'Transparency & Non-Stick Hydrocolloid Matrix',
        'hero_title': 'TEXTUREAID® CLF',
        'hero_sub': 'Specialized hydrocolloid formulation imparting translucent sheen, high cooking stability, and non-stick texture to glass noodles and pasta.',
        'stat1_num': '96%',
        'stat1_txt': 'Transparency Index',
        'stat2_num': 'Non-Stick',
        'stat2_txt': 'Strand Separation',
        'stat3_num': 'High',
        'stat3_txt': 'Hot Soup Stability',
        'image': 'assets/images/textureaid_clf.svg',
        'app': 'Clear Noodles & Glass Pasta',
        'active': 'Hydrocolloid Complex',
        'activity': 'Transparency & Texture Matrix',
        'dosage': '0.3–1.2% of flour weight',
        'spotlight': 'Enhances visual transparency, prevents clump formation post-cooking, and maintains firm texture in hot soups.',
        'meter1_title': 'Visual Sheen Transparency Index',
        'meter1_val': '96% Translucent',
        'meter1_w': '96%',
        'meter2_title': 'Non-Stick Strand Separation',
        'meter2_val': '98% Individual',
        'meter2_w': '98%',
        'meter3_title': 'Hot Soup Retort Resistance',
        'meter3_val': '95% Hold',
        'meter3_w': '95%',
        'enumbers': ['Natural Plant Hydrocolloids'],
        'b1_t': 'Crystal Transparency', 'b1_tag': 'Visual Appeal', 'b1_d': 'Imparts attractive translucent gloss to starch noodles and pasta.',
        'b2_t': 'Non-Stick Separation', 'b2_tag': 'Easy Serving', 'b2_d': 'Keeps cooked strands individual and clump-free even after standing.',
        'b3_t': 'Hot Soup Stability', 'b3_tag': 'No Softening', 'b3_d': 'Retains firm bite in boiling broths without dissolving into mush.',
        'b4_t': 'Tensile Strength', 'b4_tag': 'No Breakage', 'b4_d': 'Withstands vigorous boiling and stirring in commercial kitchens.',
        'b5_t': 'Uniform Slurry Flow', 'b5_tag': 'Smooth Extrusion', 'b5_d': 'Improves starch slurry pumping and sheet cutting.',
        'b6_t': 'Extended Hold Time', 'b6_tag': 'Buffet Ready', 'b6_d': 'Maintains fresh al dente texture under heat lamp service.',
        'sensory_val': 'It offers smooth glossy non-stick bite',
        'table_name': 'TEXTUREAID® CLF',
        'table_app': 'Clear & Starch Noodles',
        'table_active': 'Hydrocolloid Complex',
        'table_activity': 'Transparency & Texture Matrix',
        'table_dosage': '0.3% to 1.2% of flour weight',
        'table_reg': 'Conforms to FSSR 2011 / 2016 Food Safety Standards'
    },

    'product-textureaid-p.html': {
        'title': 'TEXTUREAID® P - Pastry & Bakery Dough Texturizer | Praras Biosciences',
        'meta_desc': 'TEXTUREAID® P by Praras Biosciences: Hydrocolloid & emulsifier texturizer for puff pastry and sweet doughs. Enhances flakiness, locks fat, and extends freshness.',
        'og_title': 'TEXTUREAID® P - Pastry & Bakery Dough Texturizer',
        'og_desc': 'Functional bakery texturizer preventing fat leakage during lamination, enhancing puff pastry lift, and retarding staling.',
        'cat_crumb': 'Bakery & Pastry Improvers',
        'cat_crumb_link': 'bread-buns-pizza-base.html',
        'badge': 'Dough Lamination & Fat Lock Complex',
        'hero_title': 'TEXTUREAID® P',
        'hero_sub': 'Functional hydrocolloid texturizer engineered for pastry, laminated doughs, and bakery items to improve moisture retention and flakiness.',
        'stat1_num': 'Max Lift',
        'stat1_txt': 'Pastry Flakiness',
        'stat2_num': 'Zero',
        'stat2_txt': 'Fat Leakage',
        'stat3_num': '+40%',
        'stat3_txt': 'Shelf Freshness',
        'image': 'assets/images/textureaid_p.svg',
        'app': 'Puff Pastry, Croissants & Sweet Doughs',
        'active': 'Hydrocolloid & Emulsifier Blend',
        'activity': 'Dough Lamination Matrix',
        'dosage': '0.5–1.5% of flour weight',
        'spotlight': 'Prevents fat leakage during lamination, maintains crumb softness, and extends baked shelf life.',
        'meter1_title': 'Pastry Lamination Layer Height',
        'meter1_val': '95% Lift',
        'meter1_w': '95%',
        'meter2_title': 'Fat Lock & Bleed Prevention',
        'meter2_val': '100% Locked',
        'meter2_w': '100%',
        'meter3_title': 'Staling Retardation Index',
        'meter3_val': '40% Fresher',
        'meter3_w': '88%',
        'enumbers': ['E-471 (Mono & Diglycerides)', 'E-415 (Xanthan Gum)'],
        'b1_t': 'Superior Flakiness', 'b1_tag': 'Max Lift', 'b1_d': 'Enhances puff pastry volume and distinct crispy layer separation.',
        'b2_t': 'Fat Locking', 'b2_tag': 'No Leakage', 'b2_d': 'Prevents butter and margarine bleed-out during sheeting and baking.',
        'b3_t': 'Extended Softness', 'b3_tag': 'Anti-Staling', 'b3_d': 'Retains fresh bakery softness over multi-day shelf distribution.',
        'b4_t': 'Freeze-Thaw Dough Stability', 'b4_tag': 'Bake-Off Ready', 'b4_d': 'Protects frozen raw pastry doughs from yeast damage and dryness.',
        'b5_t': 'Easy Dough Sheeting', 'b5_tag': 'Zero Shrinkage', 'b5_d': 'Relaxes dough elasticity for uniform pastry sheet thickness.',
        'b6_t': 'Richer Mouthfeel', 'b6_tag': 'Gourmet Bite', 'b6_d': 'Imparts a melt-in-mouth buttery mouthfeel with delicate crispness.',
        'sensory_val': 'It offers airy flaky layers with tender crumb',
        'table_name': 'TEXTUREAID® P',
        'table_app': 'Puff Pastry & Bakery Doughs',
        'table_active': 'Hydrocolloid & Emulsifier Blend',
        'table_activity': 'Lamination Matrix',
        'table_dosage': '0.5% to 1.5% of flour weight',
        'table_reg': 'Conforms to FSSR 2011 / 2016 Food Safety Standards'
    },

    'product-premaycel-06.html': {
        'title': 'PREMAYCEL 06 - Vegan Eggless Mayonnaise Premix | Praras Biosciences',
        'meta_desc': 'PREMAYCEL 06 by Praras Biosciences: 100% vegan eggless mayonnaise premix. Delivers creamy mouthfeel, zero oil separation, and saves up to 30% on raw material costs.',
        'og_title': 'PREMAYCEL 06 - Vegan Eggless Mayonnaise Premix',
        'og_desc': 'Easy-to-use plant starch premix replacing egg yolk in commercial mayonnaise with superior emulsion stability and velvety taste.',
        'cat_crumb': 'Mayonnaise Premix',
        'cat_crumb_link': 'mayonnaise.html',
        'badge': '100% Vegan Eggless Emulsion Binding Matrix',
        'hero_title': 'PREMAYCEL 06',
        'hero_sub': 'Complete vegan premix formulation for commercial eggless mayonnaise and salad dressings, ensuring thick creamy texture and zero oil separation.',
        'stat1_num': '100%',
        'stat1_txt': 'Eggless Vegan',
        'stat2_num': 'Zero',
        'stat2_txt': 'Oil Separation',
        'stat3_num': '+30%',
        'stat3_txt': 'Batch Cost Savings',
        'image': 'assets/images/premaycel_06.svg',
        'app': 'Eggless Mayonnaise & Salad Dressings',
        'active': 'Modified Starch & Hydrocolloid Blend',
        'activity': 'High Emulsion Binding',
        'dosage': 'Standard Batch Formula',
        'spotlight': 'Completely replaces egg yolk, lowers raw material costs by up to 30%, and maintains shelf-stable emulsion integrity.',
        'meter1_title': 'Emulsion Stability & Anti-Splitting',
        'meter1_val': '100% Hold',
        'meter1_w': '100%',
        'meter2_title': 'Spoonable Creaminess Index',
        'meter2_val': '96% Creamy',
        'meter2_w': '96%',
        'meter3_title': 'Raw Material Cost ROI',
        'meter3_val': '30% Savings',
        'meter3_w': '92%',
        'enumbers': ['E-1422 (Modified Starch)', 'E-415 (Xanthan Gum)'],
        'b1_t': '100% Eggless Vegan', 'b1_tag': 'Plant-Based', 'b1_d': 'Formulated entirely from plant starches and gums for vegetarian compliance.',
        'b2_t': 'Zero Oil Separation', 'b2_tag': 'Stable Emulsion', 'b2_d': 'Prevents syneresis and oil splitting under temperature swings and transport.',
        'b3_t': 'Rich Creamy Mouthfeel', 'b3_tag': 'Gourmet Taste', 'b3_d': 'Replicates the velvety body and spoonability of egg mayonnaise.',
        'b4_t': 'Cold-Process Ready', 'b4_tag': 'No Heating', 'b4_d': 'Blends easily in high-shear mixers without thermal cooking steps.',
        'b5_t': 'Acid & Shear Resistance', 'b5_tag': 'pH Stable', 'b5_d': 'Maintains firm body in vinegar and lemon juice formulations.',
        'b6_t': 'Significant Cost Savings', 'b6_tag': 'Up to 30% ROI', 'b6_d': 'Lowers cost per batch compared to egg yolk powder.',
        'sensory_val': 'It offers thick spoonable velvety texture',
        'table_name': 'PREMAYCEL 06',
        'table_app': 'Mayonnaise & Dressings',
        'table_active': 'Modified Starch & Hydrocolloid Blend',
        'table_activity': 'High Emulsion Binding',
        'table_dosage': 'Per Batch Recipe',
        'table_reg': 'Conforms to FSSR 2011 / 2016 Food Safety Standards'
    },

    'product-premaycel-07.html': {
        'title': 'PREMAYCEL 07 - Concentrated Mayonnaise Stabilizer | Praras Biosciences',
        'meta_desc': 'PREMAYCEL 07 by Praras Biosciences: High-potency concentrated vegan mayonnaise stabilizer delivering heat stability, high-shear resistance, and rich body.',
        'og_title': 'PREMAYCEL 07 - Concentrated Mayonnaise Stabilizer',
        'og_desc': 'Concentrated vegan hydrocolloid stabilizer delivering high heat stability, shear resistance, and glossy texture in dips and mayonnaise.',
        'cat_crumb': 'Mayonnaise Premix',
        'cat_crumb_link': 'mayonnaise.html',
        'badge': 'High-Potency Concentrated Emulsion Matrix',
        'hero_title': 'PREMAYCEL 07',
        'hero_sub': 'High-potency concentrated vegan mayonnaise stabilizer delivering exceptional heat stability, high-shear resistance, and rich body.',
        'stat1_num': 'Concentrated',
        'stat1_txt': 'Low Dosage Formula',
        'stat2_num': 'Heat-Stable',
        'stat2_txt': 'Burger & Bake Ready',
        'stat3_num': 'High',
        'stat3_txt': 'Shear Resistance',
        'image': 'assets/images/premaycel_07.svg',
        'app': 'Commercial Mayonnaise & Dips',
        'active': 'Concentrated Hydrocolloid Matrix',
        'activity': 'High Shear Stability',
        'dosage': 'Low Dosage Concentrate',
        'spotlight': 'Ideal for industrial scale producers requiring low inventory dosage, superior emulsification, and heat-resistant sauce stability.',
        'meter1_title': 'Heat & Bake Emulsion Hold',
        'meter1_val': '98% Stable',
        'meter1_w': '98%',
        'meter2_title': 'High-Shear Line Resistance',
        'meter2_val': '97% Hold',
        'meter2_w': '97%',
        'meter3_title': 'Glossy Surface Finish',
        'meter3_val': '95% Shiny',
        'meter3_w': '95%',
        'enumbers': ['E-1422 (Modified Starch)', 'E-415 (Xanthan Gum)', 'E-412 (Guar Gum)'],
        'b1_t': 'Concentrated Efficiency', 'b1_tag': 'Low Inventory', 'b1_d': 'Concentrated formula allows reduced storage footprint and low dosage.',
        'b2_t': 'Heat & Bake Stability', 'b2_tag': 'Burger Ready', 'b2_d': 'Holds emulsion structure when applied to hot burgers and baked wraps.',
        'b3_t': 'High-Shear Resistance', 'b3_tag': 'Industrial Line', 'b3_d': 'Withstands aggressive inline homogenizers without breakdown.',
        'b4_t': 'Smooth Glossy Finish', 'b4_tag': 'Visual Elegance', 'b4_d': 'Imparts an attractive shiny finish with zero dullness.',
        'b5_t': 'Syneresis Prevention', 'b5_tag': 'Extended Shelf', 'b5_d': 'Locks free moisture to prevent water weeping over months.',
        'b6_t': 'Versatile Base', 'b6_tag': 'Flavored Mayos', 'b6_d': 'Perfect carrier for garlic, mint, tandoori, and spicy flavored mayonnaise.',
        'sensory_val': 'It offers firm shiny heat-stable body',
        'table_name': 'PREMAYCEL 07',
        'table_app': 'Commercial Mayonnaise & Dips',
        'table_active': 'Concentrated Hydrocolloid Matrix',
        'table_activity': 'High Shear & Heat Stability',
        'table_dosage': 'Per Batch Concentrate Recipe',
        'table_reg': 'Conforms to FSSR 2011 / 2016 Food Safety Standards'
    },

    'product-colouraid-03.html': {
        'title': 'COLOURAID 03 - Natural Color Stabilizer & Fixative | Praras Biosciences',
        'meta_desc': 'COLOURAID 03 by Praras Biosciences: Food-grade color stabilizer protecting natural pigments in beverages, bakery, and confections from light and UV fading.',
        'og_title': 'COLOURAID 03 - Natural Color Stabilizer & Fixative',
        'og_desc': 'Antioxidant color fixative preventing UV light fading and thermal color shift in beverages, candies, and bakery products.',
        'cat_crumb': 'Food Additives',
        'cat_crumb_link': 'index.html#products',
        'badge': 'Antioxidant Pigment Lock Matrix',
        'hero_title': 'COLOURAID 03',
        'hero_sub': 'Food-grade color stabilizer designed to protect natural and synthetic pigments in beverages, confections, and baked goods from light oxidation.',
        'stat1_num': '96%',
        'stat1_txt': 'Color Retention',
        'stat2_num': 'Zero',
        'stat2_txt': 'UV Fading',
        'stat3_num': 'Clean Label',
        'stat3_txt': 'Antioxidant Complex',
        'image': 'assets/images/colouraid_03.svg',
        'app': 'Beverages, Bakery & Confectionery',
        'active': 'Natural Antioxidant & Color Lock Complex',
        'activity': 'Pigment Stabilization Matrix',
        'dosage': '0.05–0.3% of total formula',
        'spotlight': 'Prevents fading, browning, and color shift caused by UV light, heat processing, and shelf exposure.',
        'meter1_title': 'UV Light Fading Resistance',
        'meter1_val': '96% Retained',
        'meter1_w': '96%',
        'meter2_title': 'Thermal Processing Color Hold',
        'meter2_val': '95% Hold',
        'meter2_w': '95%',
        'meter3_title': 'Anti-Browning Protection Rate',
        'meter3_val': '99% Clean',
        'meter3_w': '99%',
        'enumbers': ['Natural Antioxidant Extracts (E-300 / E-307 Matrix)'],
        'b1_t': 'UV Light Protection', 'b1_tag': 'Zero Fading', 'b1_d': 'Protects colors packaged in clear glass and PET bottles from sunlight fading.',
        'b2_t': 'Thermal Color Lock', 'b2_tag': 'Heat Stable', 'b2_d': 'Retains vibrant shades through pasteurization, baking, and UHT processing.',
        'b3_t': 'Anti-Browning Guard', 'b3_tag': 'Fresh Look', 'b3_d': 'Prevents unwanted oxidative browning in fruit juices and candies.',
        'b4_t': 'Neutral Taste & Odor', 'b4_tag': 'Zero Flavor Impact', 'b4_d': 'Maintains pure product flavor without medicinal aftertaste.',
        'b5_t': 'pH Range Versatility', 'b5_tag': 'Broad Use', 'b5_d': 'Performs consistently across acidic beverages and neutral bakery items.',
        'b6_t': 'Extended Shelf Color', 'b6_tag': 'Vibrant Display', 'b6_d': 'Keeps products looking factory-fresh on store shelves longer.',
        'sensory_val': 'It offers vibrant brilliant stable shade',
        'table_name': 'COLOURAID 03',
        'table_app': 'Beverages & Food Coloration',
        'table_active': 'Natural Antioxidant Color Lock Complex',
        'table_activity': 'Pigment Stabilization Matrix',
        'table_dosage': '0.05% to 0.3% of total formulation',
        'table_reg': 'Conforms to FSSR 2011 / 2016 Food Safety Standards'
    },

    'product-hifoamaid-60.html': {
        'title': 'HIFOAMAID® 60 - Beverage Foam & Head Stabilizer | Praras Biosciences',
        'meta_desc': 'HIFOAMAID® 60 by Praras Biosciences: Specialized beverage foam enhancer delivering dense creamy head, prolonged foam retention, and lacing in carbonated drinks.',
        'og_title': 'HIFOAMAID® 60 - Beverage Foam & Head Stabilizer',
        'og_desc': 'Specialized beverage foam enhancer building a dense creamy head collar and prolonged glass lacing in carbonated beverages.',
        'cat_crumb': 'Beverage Additives',
        'cat_crumb_link': 'breweries.html',
        'badge': 'Beverage Foam Stabilization Matrix',
        'hero_title': 'HIFOAMAID® 60',
        'hero_sub': 'Specialized beverage foam enhancer providing dense creamy head, prolonged foam retention, and lacing in carbonated & malt beverages.',
        'stat1_num': '+120s',
        'stat1_txt': 'Foam Head Standing',
        'stat2_num': 'Dense',
        'stat2_txt': 'Micro-Bubbles',
        'stat3_num': '10–50 ppm',
        'stat3_txt': 'Ultra Low Dosage',
        'image': 'assets/images/hifoamaid_60.svg',
        'app': 'Carbonated Beverages, Beer & Drinks',
        'active': 'Food Hydrocolloid & Protein Fraction',
        'activity': 'Foam Stabilization Index',
        'dosage': '10–50 ppm',
        'spotlight': 'Delivers fine micro-bubbles, enhances foam cling on glass walls, and improves mouthfeel without affecting clarity.',
        'meter1_title': 'Foam Head Retention Time',
        'meter1_val': '+120s Extended',
        'meter1_w': '95%',
        'meter2_title': 'Micro-Bubble Uniformity',
        'meter2_val': '98% Dense',
        'meter2_w': '98%',
        'meter3_title': 'Glass Wall Lacing Index',
        'meter3_val': '94% Cling',
        'meter3_w': '94%',
        'enumbers': ['E-405 (PGA)', 'Natural Plant Fractions'],
        'b1_t': 'Dense Micro-Foam Head', 'b1_tag': 'Creamy Crown', 'b1_d': 'Builds a thick compact foam collar with tiny uniform bubbles.',
        'b2_t': 'Prolonged Foam Standing', 'b2_tag': 'Lasting Collar', 'b2_d': 'Extends head retention time significantly in the glass.',
        'b3_t': 'Glass Wall Lacing', 'b3_tag': 'Premium Visual', 'b3_d': 'Leaves appealing lace rings as the beverage is consumed.',
        'b4_t': 'High Acid & Alcohol Tolerance', 'b4_tag': 'Versatile Use', 'b4_d': 'Works effectively in low pH drinks and alcoholic beverages.',
        'b5_t': 'Crystal Clear Liquid', 'b5_tag': 'Zero Turbidity', 'b5_d': 'Does not cause haze or sediment in the main liquid body.',
        'b6_t': 'Low Dosage Efficiency', 'b6_tag': 'Ultra Economic', 'b6_d': 'Requires minimal ppm dosing for maximum foam performance.',
        'sensory_val': 'It offers thick creamy long-lasting head',
        'table_name': 'HIFOAMAID® 60',
        'table_app': 'Beverages & Brewed Drinks',
        'table_active': 'Food Hydrocolloid & Protein Fraction',
        'table_activity': 'High Foam Retention Matrix',
        'table_dosage': '10 to 50 ppm',
        'table_reg': 'Conforms to FSSR 2011 / 2016 Food Safety Standards'
    },

    'product-hifoamaid-62.html': {
        'title': 'HIFOAMAID® 62 - High-Performance Beverage Foaming Agent | Praras Biosciences',
        'meta_desc': 'HIFOAMAID® 62 by Praras Biosciences: Instant beverage foaming agent engineered for RTD teas, coffees, and soft drinks to create rich velvety foam layers.',
        'og_title': 'HIFOAMAID® 62 - High-Performance Beverage Foaming Agent',
        'og_desc': 'Instant foaming botanical complex generating rich velvety cream layers in RTD coffees, teas, and soft drinks.',
        'cat_crumb': 'Beverage Additives',
        'cat_crumb_link': 'chocolate-coffee.html',
        'badge': 'Instant Foaming Botanical Complex',
        'hero_title': 'HIFOAMAID® 62',
        'hero_sub': 'High-performance beverage foaming agent engineered for RTD teas, coffees, and soft drinks to create rich velvety foam layers.',
        'stat1_num': 'Instant',
        'stat1_txt': 'Foam Crown',
        'stat2_num': 'Velvety',
        'stat2_txt': 'Rich Mouthfeel',
        'stat3_num': '20–80 ppm',
        'stat3_txt': 'Dosage Rate',
        'image': 'assets/images/hifoamaid_62.svg',
        'app': 'RTD Coffee, Milk Teas & Soft Drinks',
        'active': 'Saponin & Hydrocolloid Blend',
        'activity': 'Instant Foaming Matrix',
        'dosage': '20–80 ppm',
        'spotlight': 'Instantly generates voluminous creamy foam upon dispensing, shaking, or nitrogenation.',
        'meter1_title': 'Instant Dispense Foam Volume',
        'meter1_val': '99% Volume',
        'meter1_w': '99%',
        'meter2_title': 'Cream Layer Density Index',
        'meter2_val': '95% Dense',
        'meter2_w': '95%',
        'meter3_title': 'Acid & Cold Temp Hold',
        'meter3_val': '96% Hold',
        'meter3_w': '96%',
        'enumbers': ['Natural Plant Saponins & Hydrocolloids'],
        'b1_t': 'Instant Foam Generation', 'b1_tag': 'Quick Crown', 'b1_d': 'Creates rich foam head instantly upon pouring or machine dispensing.',
        'b2_t': 'Smooth Creamy Mouthfeel', 'b2_tag': 'Velvety Taste', 'b2_d': 'Enhances beverage richness and luxurious mouthfeel.',
        'b3_t': 'Heat & Cold Stable', 'b3_tag': 'Ice & Hot Drinks', 'b3_d': 'Performs in iced coffees as well as hot RTD tea drinks.',
        'b4_t': 'Dairy & Plant Milk Compatible', 'b4_tag': 'Versatile Base', 'b4_d': 'Blends smoothly with dairy, oat, soy, and almond bases.',
        'b5_t': 'Clean Label Plant Origin', 'b5_tag': 'Natural Source', 'b5_d': 'Derived from natural plant sources for clean ingredient declaration.',
        'b6_t': 'Low Taste Threshold', 'b6_tag': 'Pure Flavor', 'b6_d': 'Preserves true coffee and tea aromatic notes.',
        'sensory_val': 'It offers rich velvety long-standing cream',
        'table_name': 'HIFOAMAID® 62',
        'table_app': 'RTD Coffee & Beverage Drinks',
        'table_active': 'Saponin & Hydrocolloid Blend',
        'table_activity': 'Instant Foaming Matrix',
        'table_dosage': '20 to 80 ppm',
        'table_reg': 'Conforms to FSSR 2011 / 2016 Food Safety Standards'
    },

    'product-hifoamaid-80.html': {
        'title': 'HIFOAMAID® 80 - Industrial Beverage & Cider Foam Booster | Praras Biosciences',
        'meta_desc': 'HIFOAMAID® 80 by Praras Biosciences: Concentrated beverage foam fixative formulated for high-carbonation beverages, ciders, and specialty beers.',
        'og_title': 'HIFOAMAID® 80 - Industrial Beverage & Cider Foam Booster',
        'og_desc': 'Ultra foam fixative resisting oil collapse and maintaining stable head crowns under high carbonation in ciders and beers.',
        'cat_crumb': 'Beverage Additives',
        'cat_crumb_link': 'breweries.html',
        'badge': 'High-Carbonation Ultra Foam Fixative',
        'hero_title': 'HIFOAMAID® 80',
        'hero_sub': 'Concentrated beverage foam fixative formulated for high-carbonation beverages, ciders, and specialty beers.',
        'stat1_num': '+150s',
        'stat1_txt': 'Head Retention',
        'stat2_num': 'Oil-Proof',
        'stat2_txt': 'Collapse Protection',
        'stat3_num': '10–40 ppm',
        'stat3_txt': 'Low Dosing',
        'image': 'assets/images/hifoamaid_80.svg',
        'app': 'High-Carbonation Drinks & Ciders',
        'active': 'Concentrated PGA & Hydrocolloid',
        'activity': 'Ultra Foam Fixative',
        'dosage': '10–40 ppm',
        'spotlight': 'Maintains robust foam stability even under high carbonation pressure and presence of natural fruit oils.',
        'meter1_title': 'Fruit Oil Collapse Resistance',
        'meter1_val': '95% Shielded',
        'meter1_w': '95%',
        'meter2_title': 'High Carbonation Pressure Hold',
        'meter2_val': '99% Hold',
        'meter2_w': '99%',
        'meter3_title': 'Liquid Clarity Preservation',
        'meter3_val': 'Zero Haze',
        'meter3_w': '98%',
        'enumbers': ['E-405 (Propylene Glycol Alginate)'],
        'b1_t': 'Oil Collapse Resistance', 'b1_tag': 'Fruit Safe', 'b1_d': 'Prevents foam breakdown caused by natural citrus or apple skin oils.',
        'b2_t': 'Extreme Head Retention', 'b2_tag': 'Long Stand', 'b2_d': 'Delivers long-lasting foam collar under commercial serving conditions.',
        'b3_t': 'High Pressure Stability', 'b3_tag': 'Carbonated Lines', 'b3_d': 'Withstands aggressive keg tap and bottle carbonation pressure.',
        'b4_t': 'Crystal Clarity Protection', 'b4_tag': 'No Haze', 'b4_d': 'Maintains sparkling clear liquid appearance without fogging.',
        'b5_t': 'Concentrated Efficiency', 'b5_tag': 'Ultra Low Dose', 'b5_d': 'Achieves maximum foam persistence with minimal ppm addition.',
        'b6_t': 'Reliable Shelf Stability', 'b6_tag': 'Long Storage', 'b6_d': 'Does not degrade over long beverage warehouse storage periods.',
        'sensory_val': 'It offers ultra-stable crisp white head',
        'table_name': 'HIFOAMAID® 80',
        'table_app': 'Ciders & Carbonated Drinks',
        'table_active': 'Concentrated PGA & Hydrocolloid',
        'table_activity': 'Ultra Foam Fixative Matrix',
        'table_dosage': '10 to 40 ppm',
        'table_reg': 'Conforms to FSSR 2011 / 2016 Food Safety Standards'
    },

    'product-hifoamaid-92.html': {
        'title': 'HIFOAMAID® 92 - Specialty Craft Beverage & NA Beer Foamer | Praras Biosciences',
        'meta_desc': 'HIFOAMAID® 92 by Praras Biosciences: Executive-grade foaming solution for craft beverages, non-alcoholic beers, and mocktails, providing dense foam crowns.',
        'og_title': 'HIFOAMAID® 92 - Craft Beverage & NA Beer Foamer',
        'og_desc': 'Botanical foaming complex tailored for 0.0% non-alcoholic beers and craft mocktails, creating velvety micro-bubble crowns.',
        'cat_crumb': 'Beverage Additives',
        'cat_crumb_link': 'breweries.html',
        'badge': '0.0% NA Beer & Craft Foaming Complex',
        'hero_title': 'HIFOAMAID® 92',
        'hero_sub': 'Executive-grade foaming solution for craft beverages, non-alcoholic beers, and mocktails, providing dense, velvety foam crowns.',
        'stat1_num': '0.0% NA',
        'stat1_txt': 'Beer Foam Restored',
        'stat2_num': 'Dense',
        'stat2_txt': 'Velvet Crown',
        'stat3_num': '15–50 ppm',
        'stat3_txt': 'Dosage Rate',
        'image': 'assets/images/hifoamaid_92.svg',
        'app': 'Craft Beverages, NA Beers & Mocktails',
        'active': 'Premium Botanical Foaming Complex',
        'activity': 'Dense Velvet Crown Matrix',
        'dosage': '15–50 ppm',
        'spotlight': 'Tailored for 0.0% non-alcoholic beers and premium craft beverages where natural foam restoration is critical.',
        'meter1_title': 'NA Beer Head Restoration',
        'meter1_val': '98% Restored',
        'meter1_w': '98%',
        'meter2_title': 'Micro-Bubble Uniformity',
        'meter2_val': '99% Fine',
        'meter2_w': '99%',
        'meter3_title': 'Glassware Creamy Lacing',
        'meter3_val': '96% Lacing',
        'meter3_w': '96%',
        'enumbers': ['Botanical Foaming Extracts & Hydrocolloids'],
        'b1_t': 'Non-Alcoholic Beer Restoration', 'b1_tag': '0.0% NA Safe', 'b1_d': 'Restores authentic brewery foam collar to 0.0% alcohol-free beers.',
        'b2_t': 'Fine Uniform Micro-Bubbles', 'b2_tag': 'Velvet Crown', 'b2_d': 'Creates an ultra-dense creamy white crown that holds for minutes.',
        'b3_t': 'Premium Craft Aesthetic', 'b3_tag': 'Tap & Bottle', 'b3_d': 'Enhances visual presentation for draft taps and bottled craft drinks.',
        'b4_t': '100% Plant Botanical Origin', 'b4_tag': 'Vegan Friendly', 'b4_d': 'Natural plant-derived formulation suitable for vegan beverages.',
        'b5_t': 'Instant Action on Dispensing', 'b5_tag': 'Quick Head', 'b5_d': 'Generates immediate head volume upon tap pour or bottle opening.',
        'b6_t': 'Smooth Taste Profile', 'b6_tag': 'Aroma Retained', 'b6_d': 'Complements delicate hop and malt aroma profiles perfectly.',
        'sensory_val': 'It offers dense micro-bubble velvet crown',
        'table_name': 'HIFOAMAID® 92',
        'table_app': 'Craft & Non-Alcoholic Beverages',
        'table_active': 'Botanical Foaming Complex',
        'table_activity': 'Dense Velvet Crown Matrix',
        'table_dosage': '15 to 50 ppm',
        'table_reg': 'Conforms to FSSR 2011 / 2016 Food Safety Standards'
    },

    'product-a-hango.html': {
        'title': 'A-HANGO - Anti-Hangover Functional Beverage Additive | Praras Biosciences',
        'meta_desc': 'A-HANGO by Praras Biosciences: Innovative functional formulation for anti-hangover drinks and herbal wellness formulations to support liver metabolism and hydration.',
        'og_title': 'A-HANGO - Anti-Hangover Functional Beverage Additive',
        'og_desc': 'Botanical & electrolyte bioactive formulation supporting acetaldehyde breakdown, liver recovery, and morning-after revitalization.',
        'cat_crumb': 'Functional Beverages',
        'cat_crumb_link': 'index.html#products',
        'badge': 'Functional Bioactive & Electrolyte Complex',
        'hero_title': 'A-HANGO',
        'hero_sub': 'Innovative functional formulation designed for anti-hangover drinks and herbal wellness formulations to support liver metabolism and hydration.',
        'stat1_num': 'Metabolic',
        'stat1_txt': 'Acetaldehyde Cut',
        'stat2_num': 'Natural',
        'stat2_txt': 'Herbal Extract Blend',
        'stat3_num': 'Rapid',
        'stat3_txt': 'Hydration Boost',
        'image': 'assets/images/a_hango.svg',
        'app': 'Wellness Beverages & Anti-Hangover Drinks',
        'active': 'Botanical Extracts & Electrolytes',
        'activity': 'Functional Bioactive Matrix',
        'dosage': 'Per Recommended Serving Dosing',
        'spotlight': 'Supports alcohol breakdown pathways, reduces acetaldehyde discomfort, and accelerates morning-after revitalization.',
        'meter1_title': 'Acetaldehyde Metabolism Support',
        'meter1_val': '95% Efficiency',
        'meter1_w': '95%',
        'meter2_title': 'Bioactive Water Solubilization',
        'meter2_val': '98% Clear',
        'meter2_w': '98%',
        'meter3_title': 'Herbal Bitterness Masking Rate',
        'meter3_val': '94% Masked',
        'meter3_w': '94%',
        'enumbers': ['Natural Botanical & Bioactive Complex'],
        'b1_t': 'Acetaldehyde Support', 'b1_tag': 'Next-Day Vitality', 'b1_d': 'Helps metabolic breakdown of alcohol byproducts for next-day vitality.',
        'b2_t': 'Electrolyte & Hydration', 'b2_tag': 'Mineral Boost', 'b2_d': 'Replenishes essential minerals lost during social drinking.',
        'b3_t': 'Herbal Liver Support', 'b3_tag': 'Hepatic Care', 'b3_d': 'Enriched with natural botanical extracts renowned for hepatic wellness.',
        'b4_t': 'High Water Solubilization', 'b4_tag': 'Crystal Clear', 'b4_d': 'Dissolves crystal-clear in shot drinks, RTDs, and effervescent tablets.',
        'b5_t': 'Advanced Taste Masking', 'b5_tag': 'Great Taste', 'b5_d': 'Masks bitter herbal notes with pleasant refreshing flavor notes.',
        'b6_t': 'Rapid Absorption', 'b6_tag': 'Fast Bioavailability', 'b6_d': 'Engineered for quick bioavailability and rapid digestive absorption.',
        'sensory_val': 'It offers smooth refreshing bio-active drink',
        'table_name': 'A-HANGO',
        'table_app': 'Wellness & Anti-Hangover Beverages',
        'table_active': 'Botanical Extracts & Electrolytes',
        'table_activity': 'Functional Bioactive Matrix',
        'table_dosage': 'Per Recommended Serving Dosing',
        'table_reg': 'Conforms to FSSR 2011 / 2016 Food Safety Standards'
    }
}

print(f"Loaded configuration for {len(PRODUCTS)} products.")

def generate_page(file_name, data):
    # Perform substitutions on sample2_html
    html = sample2_html
    
    # Title & Meta Tags
    html = re.sub(r'<title>.*?</title>', f'<title>{data["title"]}</title>', html)
    html = re.sub(r'<meta name="description" content=".*?">', f'<meta name="description" content="{data["meta_desc"]}">', html)
    html = re.sub(r'<link rel="canonical" href=".*?">', f'<link rel="canonical" href="https://www.prarasbiosciences.com/{file_name}">', html)
    html = re.sub(r'<meta property="og:title" content=".*?">', f'<meta property="og:title" content="{data["og_title"]}">', html)
    html = re.sub(r'<meta property="og:description" content=".*?">', f'<meta property="og:description" content="{data["og_desc"]}">', html)
    html = re.sub(r'<meta property="og:url" content=".*?">', f'<meta property="og:url" content="https://www.prarasbiosciences.com/{file_name}">', html)
    html = re.sub(r'<meta name="twitter:title" content=".*?">', f'<meta name="twitter:title" content="{data["og_title"]}">', html)
    html = re.sub(r'<meta name="twitter:description" content=".*?">', f'<meta name="twitter:description" content="{data["og_desc"]}">', html)
    
    # Image in meta & body
    html = re.sub(r'assets/images/biscamaze_lf.svg', data['image'], html)
    
    # Breadcrumb
    html = re.sub(r'<a href="biscuits-cookies.html">Biscuit Improvers</a>', f'<a href="{data["cat_crumb_link"]}">{data["cat_crumb"]}</a>', html)
    html = re.sub(r'<span style="color: var\(--wc-gold-light\);">BISCAMAZE® LF</span>', f'<span style="color: var(--wc-gold-light);">{data["hero_title"]}</span>', html)
    
    # Badge Pill & Hero Title
    html = re.sub(r'<span class="wc-badge-dot"></span>\s*Protease \(E-1101\) Formulation', f'<span class="wc-badge-dot"></span>\n        {data["badge"]}', html)
    html = re.sub(r'<h1 class="wc-hero-title">BISCAMAZE® LF</h1>', f'<h1 class="wc-hero-title">{data["hero_title"]}</h1>', html)
    
    # Hero Subtitle
    html = re.sub(r'<p class="wc-hero-sub">\s*Precision enzymatic formulation designed for commercial biscuit &amp; cookie manufacturers to optimize dough rheology, enhance stack height, and cut ingredient costs\.\s*</p>',
                  f'<p class="wc-hero-sub">\n        {data["hero_sub"]}\n      </p>', html)
    
    # Stat Chips
    html = re.sub(r'<div class="wc-hero-stat-num">\+5%</div>\s*<div class="wc-hero-stat-txt">Stack Height Gain</div>',
                  f'<div class="wc-hero-stat-num">{data["stat1_num"]}</div>\n          <div class="wc-hero-stat-txt">{data["stat1_txt"]}</div>', html)
    html = re.sub(r'<div class="wc-hero-stat-num">Up to 20%</div>\s*<div class="wc-hero-stat-txt">Fat Reduction</div>',
                  f'<div class="wc-hero-stat-num">{data["stat2_num"]}</div>\n          <div class="wc-hero-stat-txt">{data["stat2_txt"]}</div>', html)
    html = re.sub(r'<div class="wc-hero-stat-num">40–60%</div>\s*<div class="wc-hero-stat-txt">SMBS Usage Cut</div>',
                  f'<div class="wc-hero-stat-num">{data["stat3_num"]}</div>\n          <div class="wc-hero-stat-txt">{data["stat3_txt"]}</div>', html)
    
    # Data Product attribute for Quote Buttons
    html = re.sub(r'data-product="BISCAMAZE® LF"', f'data-product="{data["table_name"]}"', html)
    
    # Quick Specs Bento (Tab 1)
    html = re.sub(r'<div class="wc-bento-val">Biscuits &amp; Cookies</div>', f'<div class="wc-bento-val">{data["app"]}</div>', html)
    html = re.sub(r'<div class="wc-bento-val">Protease \(E‑1101\)</div>', f'<div class="wc-bento-val">{data["active"]}</div>', html)
    html = re.sub(r'<div class="wc-bento-val">NLT 12,000 TU/g</div>', f'<div class="wc-bento-val">{data["activity"]}</div>', html)
    html = re.sub(r'<div class="wc-bento-val">20–100 g / 100 kg flour</div>', f'<div class="wc-bento-val">{data["dosage"]}</div>', html)
    
    # Spotlight
    html = re.sub(r'<p class="wc-function-body">\s*Enhances browning and crispiness, boosts stack height by 5%, cuts fat up to 20% and SMBS by 40–60%—all with cost‑effective efficiency\.\s*</p>',
                  f'<p class="wc-function-body">\n              {data["spotlight"]}\n            </p>', html)
    
    # Meters (Tab 2)
    html = re.sub(r'<span>Biscuit Stack Height Gain</span>\s*<span class="wc-meter-val">\+5% Gain</span>',
                  f'<span>{data["meter1_title"]}</span>\n                <span class="wc-meter-val">{data["meter1_val"]}</span>', html)
    html = re.sub(r'<div class="wc-meter-fill" style="width: 92%;"></div>', f'<div class="wc-meter-fill" style="width: {data["meter1_w"]};"></div>', html)
    
    html = re.sub(r'<span>Fat Content Reduction Capacity</span>\s*<span class="wc-meter-val">Up to 20% Cut</span>',
                  f'<span>{data["meter2_title"]}</span>\n                <span class="wc-meter-val">{data["meter2_val"]}</span>', html)
    html = re.sub(r'<div class="wc-meter-fill" style="width: 85%;"></div>', f'<div class="wc-meter-fill" style="width: {data["meter2_w"]};"></div>', html)
    
    html = re.sub(r'<span>SMBS Additive Usage Reduction</span>\s*<span class="wc-meter-val">40–60% Reduction</span>',
                  f'<span>{data["meter3_title"]}</span>\n                <span class="wc-meter-val">{data["meter3_val"]}</span>', html)
    html = re.sub(r'<div class="wc-meter-fill" style="width: 90%;"></div>', f'<div class="wc-meter-fill" style="width: {data["meter3_w"]};"></div>', html)
    
    # E-numbers Pills (Tab 3)
    etag_html = '\n'.join([f'              <span class="wc-etag-pill">{e}</span>' for e in data['enumbers']])
    html = re.sub(r'<div class="wc-etag-row">.*?</div>', f'<div class="wc-etag-row">\n{etag_html}\n            </div>', html, flags=re.DOTALL)
    
    # Bento Benefits (3x2)
    html = re.sub(r'<span>Texture &amp; Browning</span>\s*<span class="wc-bcard-tag">Crispy Bite</span>', f'<span>{data["b1_t"]}</span>\n            <span class="wc-bcard-tag">{data["b1_tag"]}</span>', html)
    html = re.sub(r'<p class="wc-bcard-desc">Improves texture and overall quality such as browning and crispiness in biscuits and crackers\.</p>', f'<p class="wc-bcard-desc">{data["b1_d"]}</p>', html)
    
    html = re.sub(r'<span>Stack Height Boost</span>\s*<span class="wc-bcard-tag">\+5% Height</span>', f'<span>{data["b2_t"]}</span>\n            <span class="wc-bcard-tag">{data["b2_tag"]}</span>', html)
    html = re.sub(r'<p class="wc-bcard-desc">Increases biscuit stack height up to 5% with maximum cost effectiveness\.</p>', f'<p class="wc-bcard-desc">{data["b2_d"]}</p>', html)
    
    html = re.sub(r'<span>Fat Reduction</span>\s*<span class="wc-bcard-tag">Up to 20% Cut</span>', f'<span>{data["b3_t"]}</span>\n            <span class="wc-bcard-tag">{data["b3_tag"]}</span>', html)
    html = re.sub(r'<p class="wc-bcard-desc">Helps in fat reduction up to 20% or more depending on fat percentage\.</p>', f'<p class="wc-bcard-desc">{data["b3_d"]}</p>', html)
    
    html = re.sub(r'<span>SMBS Reduction</span>\s*<span class="wc-bcard-tag">40–60% Cut</span>', f'<span>{data["b4_t"]}</span>\n            <span class="wc-bcard-tag">{data["b4_tag"]}</span>', html)
    html = re.sub(r'<p class="wc-bcard-desc">SMBS additive usage can be reduced by 40–60% in dough formulation\.</p>', f'<p class="wc-bcard-desc">{data["b4_d"]}</p>', html)
    
    html = re.sub(r'<span>Cost Efficiency</span>\s*<span class="wc-bcard-tag">Commercial ROI</span>', f'<span>{data["b5_t"]}</span>\n            <span class="wc-bcard-tag">{data["b5_tag"]}</span>', html)
    html = re.sub(r'<p class="wc-bcard-desc">Delivers substantial batch cost reduction for high-volume biscuit &amp; cookie operations\.</p>', f'<p class="wc-bcard-desc">{data["b5_d"]}</p>', html)
    
    html = re.sub(r'<span>Sensory Impression</span>\s*<span class="wc-bcard-tag">Quality Boost</span>', f'<span>{data["b6_t"]}</span>\n            <span class="wc-bcard-tag">{data["b6_tag"]}</span>', html)
    html = re.sub(r'<p class="wc-bcard-desc">Significantly elevates customer perception and product crispiness\.</p>', f'<p class="wc-bcard-desc">{data["b6_d"]}</p>', html)
    
    # Sensory Profile
    html = re.sub(r'<div class="wc-sensory-val">It offers crispy bite</div>', f'<div class="wc-sensory-val">{data["sensory_val"]}</div>', html)
    
    # Tech Table
    table_html = f'''      <table class="wc-table" role="table" aria-label="Product Technical Specifications">
        <tr>
          <td>Product Name</td>
          <td>{data["table_name"]}</td>
        </tr>
        <tr>
          <td>Application</td>
          <td>{data["table_app"]}</td>
        </tr>
        <tr>
          <td>Active Ingredient</td>
          <td>{data["table_active"]}</td>
        </tr>
        <tr>
          <td>Enzymatic Activity</td>
          <td>{data["table_activity"]}</td>
        </tr>
        <tr>
          <td>Standard Dosage</td>
          <td>{data["table_dosage"]}</td>
        </tr>
        <tr>
          <td>Regulatory Standard</td>
          <td>{data["table_reg"]}</td>
        </tr>
      </table>'''
    
    html = re.sub(r'<table class="wc-table" role="table" aria-label="Product Technical Specifications">.*?</table>', table_html, html, flags=re.DOTALL)
    
    # CTA Band Heading
    html = re.sub(r'<h2 class="cta-h">Request BISCAMAZE® LF Technical Sample</h2>', f'<h2 class="cta-h">Request {data["table_name"]} Technical Sample</h2>', html)
    
    with open(file_name, 'w', encoding='utf-8') as out_f:
        out_f.write(html)
    
    print(f"Successfully generated {file_name}")

for filename, config in PRODUCTS.items():
    generate_page(filename, config)
